project_id = "ccdlygjdizpesdblymaq"

[functions.chat]
verify_jwt = false

[functions.promoter-create]
verify_jwt = false

[functions.extract-event-details]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false